name: Generate ASCII Artwork
on:
  push:

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
      - name: List Files Before Run
        run: ls -ltra
      - name: Install, Execute, Verify Cowsay
        run: |
            chmod +x ascii-script.sh
            ./ascii-script.sh